### PR TITLE
Manage multi workspace folder and JS refacto

### PR DESCRIPTION
**Pull request by quentingodeau**
Hi, 
fist after all I am sorry for this pull request I change (maybe) to much things... I keep almost every things that you have previously code but move then (sorry for the complexity of review). I also change the way that you named variables to pascalCase. If it bother you, I can still change it.
So, what I have done in this:
- Implement multi folder workspace
- Managing of bazel sub directory ad workspace 
- Move bazel command in a specific module

### CODE REVIEW

**Comment by dprogm** [comment]
As long as everything continues to work I am very much in favor of having a more modularized solution that drives maintainability. Maybe we can wait until we've integrated issue https://github.com/dprogm/vscode-bazel-tools/pull/4? It may cause conflicts.

**Comment by quentingodeau** [comment]
Yes I thinks that a good idea to merge the #4 before :)

**Comment by dprogm** [comment]
@quentingodeau I have merged #4 into master which indeed caused conflicts. Would be nice if you can resolve them. 

I've also seen in your repo that you (re-)work a lot on the plugin. Do you have any plans with the plugin? Actually I am really glad for your work which pushes bazel integration forward ;)

**Comment by quentingodeau** [comment]
Yes thanks, I will take a look and resolve the conflict :)

I'm working on the cpp part of the plugin for the moment and I'm trying to allow multi IntelliSense configuration to match targets configuration. I'm interested if you have some idea about it, for now mine is to create one configuration by configured target/os (but I not sure that is the best idea...). Then I think I will take a look to automatically create VSCode tasks cf issue #9 (if you do not solve this before).

You may have some idea/opinion about the evolution of the plugin and how you expect contributions. One way we could do this is by creating "issues" in order to propose evolution and open the discussion on it.

**Comment by quentingodeau** [comment]
Hi,
It done I merged the master b518c2b, I also perform the change to use regex parse, that I mention into the #4 (547ae1f)

**Pull request merged**
